only webglbuild

diff --git a/.github/workflows/template.yml b/.github/workflows/template.yml
--- a/.github/workflows/template.yml
+++ b/.github/workflows/template.yml
@@ -6,26 +6,30 @@ env:
   UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
 
 jobs:
-  checkSecrets:
-    name: Check for the Unity license
+  check_variables:
     runs-on: ubuntu-latest
-    env:
-      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
-      UNITY_USER: ${{ secrets.UNITY_USER }}
-      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
     steps:
-      - name: Fail - No License in settings-secretsandvariables
-        if: ${{ !startsWith(env.UNITY_LICENSE, '<') }}
-        run: exit 1
-      - name: Fail - No UNITY_USER in settings-secretsandvariables
-        if: ${{ !startsWith(env.UNITY_USER, '') }}
-        run: exit 1
-      - name: Fail - No UNITY_PASSWORD in settings-secretsandvariables
-        if: ${{ !startsWith(env.UNITY_PASSWORD, '') }}
-        run: exit 1
+      - name: Check Variables
+        env:
+          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
+          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
+          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
+        run: |
+          if [[ -z "${UNITY_LICENSE}" ]]; then
+            echo "UNITY_LICENSE is not set. Please set the secret in the repository settings."
+            exit 1
+          fi
+          if [[ -z "${UNITY_EMAIL}" ]]; then
+            echo "UNITY_EMAIL is not set. Please set the secret in the repository settings."
+            exit 1
+          fi
+          if [[ -z "${UNITY_PASSWORD}" ]]; then
+            echo "UNITY_PASSWORD is not set. Please set the secret in the repository settings."
+            exit 1
+          fi
 
   testRunner:
-    needs: checkSecrets
+    needs: check_variables
     name: Test in ${{ matrix.testMode }} ✨
     runs-on: ubuntu-latest
     strategy:
@@ -120,93 +124,93 @@ jobs:
           name: build-WebGL
           path: build/WebGL
 
-  buildWindows:
-    needs: testRunner
-    name: Build for Windows 🖥️
-    runs-on: ubuntu-latest
-    strategy:
-      fail-fast: false
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
+  # buildWindows:
+  #   needs: testRunner
+  #   name: Build for Windows 🖥️
+  #   runs-on: ubuntu-latest
+  #   strategy:
+  #     fail-fast: false
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v2
 
-      - name: Create LFS file list
-        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id
+  #     - name: Create LFS file list
+  #       run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id
 
-      - name: Restore LFS cache
-        uses: actions/cache@v2
-        id: lfs-cache
-        with:
-          path: .git/lfs
-          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}
+  #     - name: Restore LFS cache
+  #       uses: actions/cache@v2
+  #       id: lfs-cache
+  #       with:
+  #         path: .git/lfs
+  #         key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}
 
-      - name: Git LFS Pull
-        run: |
-          git lfs pull
-          git add .
-          git reset --hard
+  #     - name: Git LFS Pull
+  #       run: |
+  #         git lfs pull
+  #         git add .
+  #         git reset --hard
 
-      - name: Restore Library cache
-        uses: actions/cache@v2
-        with:
-          path: Library
-          key: Library-build-StandaloneWindows64
-          restore-keys: |
-            Library-build-
-            Library-
+  #     - name: Restore Library cache
+  #       uses: actions/cache@v2
+  #       with:
+  #         path: Library
+  #         key: Library-build-StandaloneWindows64
+  #         restore-keys: |
+  #           Library-build-
+  #           Library-
 
-      - uses: game-ci/unity-builder@v2
-        with:
-          targetPlatform: StandaloneWindows64
+  #     - uses: game-ci/unity-builder@v2
+  #       with:
+  #         targetPlatform: StandaloneWindows64
 
-      - uses: actions/upload-artifact@v2
-        with:
-          name: build-StandaloneWindows64
-          path: build/StandaloneWindows64
+  #     - uses: actions/upload-artifact@v2
+  #       with:
+  #         name: build-StandaloneWindows64
+  #         path: build/StandaloneWindows64
 
-  buildAndroid:
-    needs: testRunner
-    name: Build for Android 📱
-    runs-on: ubuntu-latest
-    strategy:
-      fail-fast: false
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
+  # buildAndroid:
+  #   needs: testRunner
+  #   name: Build for Android 📱
+  #   runs-on: ubuntu-latest
+  #   strategy:
+  #     fail-fast: false
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v2
 
-      - name: Create LFS file list
-        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id
+  #     - name: Create LFS file list
+  #       run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id
 
-      - name: Restore LFS cache
-        uses: actions/cache@v2
-        id: lfs-cache
-        with:
-          path: .git/lfs
-          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}
+  #     - name: Restore LFS cache
+  #       uses: actions/cache@v2
+  #       id: lfs-cache
+  #       with:
+  #         path: .git/lfs
+  #         key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}
 
-      - name: Git LFS Pull
-        run: |
-          git lfs pull
-          git add .
-          git reset --hard
+  #     - name: Git LFS Pull
+  #       run: |
+  #         git lfs pull
+  #         git add .
+  #         git reset --hard
 
-      - name: Restore Library cache
-        uses: actions/cache@v2
-        with:
-          path: Library
-          key: Library-build-Android
-          restore-keys: |
-            Library-build-
-            Library-
+  #     - name: Restore Library cache
+  #       uses: actions/cache@v2
+  #       with:
+  #         path: Library
+  #         key: Library-build-Android
+  #         restore-keys: |
+  #           Library-build-
+  #           Library-
 
-      - uses: game-ci/unity-builder@v2
-        with:
-          targetPlatform: Android
+  #     - uses: game-ci/unity-builder@v2
+  #       with:
+  #         targetPlatform: Android
 
-      - uses: actions/upload-artifact@v2
-        with:
-          name: build-Android
-          path: build/Android
+  #     - uses: actions/upload-artifact@v2
+  #       with:
+  #         name: build-Android
+  #         path: build/Android
 
 
   deployPages:
